spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/nunessports
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
                ddl-auto: create

    mvc:
        cors:
            allowed-origins: "http://localhost:4200"